name: Version, build, publish

on:
  push:
    branches:
      - main

jobs:

  semantic_release_next_version:
    name: Next version
    runs-on: ubuntu-latest
    steps:
      # Checkout and run semantic release to get the next version
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - run: npx semantic-release --dry-run
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Save the modified files for future steps
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release
          path: |
            Cargo.toml
          retention-days: 1
    outputs:
      version: ${{ steps.semantic_release.outputs.version }}

  test_rust:
    name: Build Rust
    needs: semantic_release_next_version
    if: needs.semantic_release_next_version.outputs.version != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Download the new version
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release

      # Run all tests
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --release --all-features

      # Save the modified Cargo.lock file with the updated version
      - uses: actions/upload-artifact@v3
        with:
          name: semantic-release-cargo-lock
          path: |
            Cargo.lock
          retention-days: 1

  semantic_release_publish:
    name: Publish to GitHub
    needs: test_rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Download the modified lock file, the toml will be automatically updated by semantic release
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release-cargo-lock

      # Run and publish
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
      - run: npm install
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload_crates:
    name: Publish to crates.io
    needs: semantic_release_publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: semantic-release
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --allow-dirty --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
